### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-css-transitions-animations-transforms#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://zealous-screw.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/css-transitions-animations-transforms/1) criteria:
- [x] Build a table using [a `table` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#Examples), listing statistics for various branches of a national organization. Example stats should all be very impressive business terms, such as "Synergy Coefficient" or "Projected Bitcoin Dynamics". Include at least 3 stats for a very impressive table.
- [x] When the user hovers over each table cell, the background color should slowly **transition** to a different color.
- [x] When the user hovers over the table, it should **transition** to be slightly larger with a fancy **scale transform**.
- [x] When the user hovers over a table row (`tr`), the row should **transition_ to the right slightly with a __translateX transform**.
- [x] The client needs a fancy logo, so quickly create one with the [Hipster Logo Generator](https://www.hipsterlogogenerator.com/), then include it in your page, above the table. It's very important to the client that a super awesome **keyframe animation** is applied when a user hovers over the logo. (You can create your own or steal [an attention seeker from animate.css](https://github.com/daneden/animate.css/tree/master/source/attention_seekers)).

Also looks awful, but I got bored. :)

**Comment by chrisvfritz** [comment]
Looks mostly good. A couple things I noticed though:
- The animation on the logo is always running, instead of just on hover.
- When hovering over the table, it snaps to a larger size rather than slowly transitioning to a larger size.

**Comment by KatieMFritz** [comment]
fixed!

**Comment by chrisvfritz** [comment]
:shipit: :+1:
